"""Add description to groups and fix relationships

Revision ID: 5773dc816c0c
Revises: f1be57e7b9fc
Create Date: 2025-02-11 13:01:06.148305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5773dc816c0c'
down_revision: Union[str, None] = 'f1be57e7b9fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_groups_id', table_name='groups')
    op.drop_index('ix_groups_name', table_name='groups')
    op.drop_table('groups')
    op.drop_index('ix_words_id', table_name='words')
    op.drop_index('ix_words_kanji', table_name='words')
    op.drop_table('words')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('kanji', sa.TEXT(), nullable=False),
    sa.Column('romaji', sa.TEXT(), nullable=False),
    sa.Column('english', sa.TEXT(), nullable=False),
    sa.Column('parts', sa.TEXT(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_words_kanji', 'words', ['kanji'], unique=False)
    op.create_index('ix_words_id', 'words', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('words_count', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_groups_name', 'groups', ['name'], unique=False)
    op.create_index('ix_groups_id', 'groups', ['id'], unique=False)
    # ### end Alembic commands ###
