name: Backend Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'lang-portal/toki-pona-api/**'
      - '.github/workflows/backend_tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'lang-portal/toki-pona-api/**'
      - '.github/workflows/backend_tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lang-portal/toki-pona-api

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: toki_pona_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]

    - name: Run tests with coverage
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/toki_pona_test
      run: |
        pytest --cov=src --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: github.repository == 'dr-rompecabezas/free-genai-bootcamp-2025' && !github.event.pull_request.head.repo.fork
      continue-on-error: true
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        name: codecov-toki-pona
