name: Backend Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'lang-portal/backend-fastapi/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'lang-portal/backend-fastapi/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lang-portal/backend-fastapi

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build setuptools wheel
        pip install -r requirements.txt
        pip install pytest pytest-asyncio httpx
        pip install -e .

    - name: List installed packages
      run: |
        pip list

    - name: Show current directory structure
      run: |
        pwd
        ls -la
        python -c "import sys; print('\n'.join(sys.path))"

    - name: Run tests
      run: |
        PYTHONPATH=. python -m pytest tests/api/ -v
