name: Frontend Vue Tests

on:
  push:
    paths:
      - 'lang-portal/frontend-vue/**'
  pull_request:
    paths:
      - 'lang-portal/frontend-vue/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: lang-portal/frontend-vue

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: lang-portal/frontend-vue/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit
