name: Writing App Tests

on:
  push:
    paths:
      - 'writing-app/**'
  pull_request:
    paths:
      - 'writing-app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: writing-app

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install `uv`
      run: |
        curl -fsSL https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH  # Ensure `uv` is in PATH
        uv --version  # Verify installation

    - name: Sync dependencies with `uv`
      run: |
        uv sync
        uv pip list  # Debugging step to check installed packages

    - name: Activate virtual environment
      run: |
        echo "VIRTUAL_ENV=$(uv venv)" >> $GITHUB_ENV
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
        echo "Python binary: $(which python)"
        echo "Streamlit binary: $(which streamlit)"
        echo "Pytest binary: $(which pytest)"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1 ffmpeg libsm6 libxext6

    - name: Start Streamlit App (Run in Background)
      env:
        STREAMLIT_BROWSER_GATHER_USAGE_STATS: false
        STREAMLIT_SERVER_ADDRESS: localhost
        STREAMLIT_SERVER_PORT: 8501
        STREAMLIT_SERVER_HEADLESS: true
        PYTHONPATH: ${{ github.workspace }}/writing-app
      run: |
        streamlit run app.py &
        sleep 3  # Allow time for Streamlit to initialize

    - name: Create models directory
      run: mkdir -p models

    - name: Run tests with Debug Logging
      run: |
        pytest tests/test_app.py -v --log-cli-level=INFO

    - name: Run Streamlit App Action (Recommended)
      uses: streamlit/streamlit-app-action@v0.0.3
      with:
        app-path: 'writing-app/app.py'
        ruff: true
