name: Writing App Tests

on:
  push:
    paths:
      - 'writing-app/**'
  pull_request:
    paths:
      - 'writing-app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: writing-app

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install pip-tools

    - name: Generate requirements.txt
      run: pip-compile pyproject.toml

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install pytest

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx

    - name: Run tests
      run: |
        python -m pytest tests/test_app.py -v
